name: Nix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  create-images:
    strategy:
      matrix:
        target:
          - name: .#first
            latest: false
          - name: .#second
            latest: false
          - name: .#third
            latest: true
      fail-fast: true
    uses: infastin/nixpkgs-k8s/.github/workflows/base.yml@master
    with:
      target: ${{ matrix.target.name }}
      latest: ${{ matrix.target.latest }}
